#!/usr/bin/env bash
SHELL=/bin/sh PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
/home/pi/mining-rig-watchdog/test-claymore ||  {
	date +%s > /home/pi/mining-rig-watchdog/resets.log
	/home/pi/mining-rig-watchdog/reset
}

